spring:
  application:
    name: apollo-demo

server:
  port: 8000

app:
  id: app58
apollo:
  cache-dir: /opt/data/
  cluster: default
  meta: http://kimmking.cn:8080
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: true
    namespaces: demo
    eagerLoad:
      enabled: false

p:
  a: a001
  b: b001
  c:
    c01: cccc0001
    c02: cccc0002

logging:
  level:
    root: info
    org.springframework: info
    com.ctrip: info